sonar.projectKey=subingeorge-123_smart-expense-manager
sonar.organization=subingeorge-123
sonar.sources=.
sonar.exclusions=**/coverage.xml, **/tests/**, **/venv/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11